version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: meridesignhouse_postgres
    environment:
      POSTGRES_DB: meridesignhouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meridesignhouse_network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: meridesignhouse_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - meridesignhouse_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  meridesignhouse_network:
    driver: bridge
