import type { PersonalizationCatalogTemplate } from '@/types/personalization'

export const PERSONALIZATION_CATALOG_TEMPLATES: PersonalizationCatalogTemplate[] = [
  {
    id: 'template-01',
    title: 'Şablon 01',
    description: 'Minimal tipografi, modern görünüm',
    imageUrl: '/images/personalization/template-01.jpg',
    recommendedSizes: ['5x5 cm', '6x6 cm'],
    tags: ['minimal', 'modern'],
  },
  {
    id: 'template-02',
    title: 'Şablon 02',
    description: 'El yazısı başlık ve kalp detayı',
    imageUrl: '/images/personalization/template-02.jpg',
    recommendedSizes: ['6x6 cm', '8x5 cm'],
    tags: ['romantik'],
  },
  {
    id: 'template-03',
    title: 'Şablon 03',
    description: 'Altın yaldız çerçeve, klasik',
    imageUrl: '/images/personalization/template-03.jpg',
    recommendedSizes: ['7x7 cm', '8x5 cm'],
    tags: ['klasik', 'lüks'],
  },
  {
    id: 'template-04',
    title: 'Şablon 04',
    description: 'Çiçekli, akvarel detaylar',
    imageUrl: '/images/personalization/template-04.jpg',
    recommendedSizes: ['6x6 cm', '8x6 cm'],
    tags: ['çiçek', 'romantik'],
  },
  {
    id: 'template-05',
    title: 'Şablon 05',
    description: 'Geometrik form, modern çizgiler',
    imageUrl: '/images/personalization/template-05.jpg',
    recommendedSizes: ['6x6 cm', '9x5 cm'],
    tags: ['geometrik', 'modern'],
  },
  {
    id: 'template-06',
    title: 'Şablon 06',
    description: 'Yuvarlak hatlar, pastel tonlar',
    imageUrl: '/images/personalization/template-06.jpg',
    recommendedSizes: ['5x5 cm', '6x6 cm'],
    tags: ['pastel', 'minimal'],
  },
  {
    id: 'template-07',
    title: 'Şablon 07',
    description: 'Vintage mühür etkisi',
    imageUrl: '/images/personalization/template-07.jpg',
    recommendedSizes: ['7x7 cm', '8x5 cm'],
    tags: ['vintage', 'klasik'],
  },
  {
    id: 'template-08',
    title: 'Şablon 08',
    description: 'Monogram odaklı düzen',
    imageUrl: '/images/personalization/template-08.jpg',
    recommendedSizes: ['6x6 cm', '8x5 cm'],
    tags: ['monogram'],
  },
  {
    id: 'template-09',
    title: 'Şablon 09',
    description: 'Kalp sembolleri ve el yazısı',
    imageUrl: '/images/personalization/template-09.jpg',
    recommendedSizes: ['5x5 cm', '6x6 cm'],
    tags: ['romantik'],
  },
  {
    id: 'template-10',
    title: 'Şablon 10',
    description: 'Line-art illüstrasyon',
    imageUrl: '/images/personalization/template-10.jpg',
    recommendedSizes: ['6x6 cm', '8x5 cm'],
    tags: ['illüstrasyon', 'minimal'],
  },
  {
    id: 'template-11',
    title: 'Şablon 11',
    description: 'Boho desenler ve doğal tonlar',
    imageUrl: '/images/personalization/template-11.jpg',
    recommendedSizes: ['7x7 cm', '9x5 cm'],
    tags: ['boho', 'doğal'],
  },
  {
    id: 'template-12',
    title: 'Şablon 12',
    description: 'Topografik desenli fon',
    imageUrl: '/images/personalization/template-12.jpg',
    recommendedSizes: ['6x6 cm', '8x5 cm'],
    tags: ['modern'],
  },
  {
    id: 'template-13',
    title: 'Şablon 13',
    description: 'Minimal tipografi, tek satır',
    imageUrl: '/images/personalization/template-13.jpg',
    recommendedSizes: ['5x5 cm'],
    tags: ['minimal'],
  },
  {
    id: 'template-14',
    title: 'Şablon 14',
    description: 'Baskılı çerçeve ve altın yaldız',
    imageUrl: '/images/personalization/template-14.jpg',
    recommendedSizes: ['8x5 cm', '9x5 cm'],
    tags: ['lüks'],
  },
  {
    id: 'template-15',
    title: 'Şablon 15',
    description: 'Rustik kraft kağıt görünümü',
    imageUrl: '/images/personalization/template-15.jpg',
    recommendedSizes: ['6x6 cm', '8x5 cm'],
    tags: ['rustik', 'doğal'],
  },
  {
    id: 'template-16',
    title: 'Şablon 16',
    description: 'Minimal pastel degrade',
    imageUrl: '/images/personalization/template-16.jpg',
    recommendedSizes: ['6x6 cm'],
    tags: ['pastel', 'minimal'],
  },
  {
    id: 'template-17',
    title: 'Şablon 17',
    description: 'Illustrasyonlu kuş motifleri',
    imageUrl: '/images/personalization/template-17.jpg',
    recommendedSizes: ['7x7 cm'],
    tags: ['illüstrasyon', 'romantik'],
  },
  {
    id: 'template-18',
    title: 'Şablon 18',
    description: 'Art-deco çizgiler',
    imageUrl: '/images/personalization/template-18.jpg',
    recommendedSizes: ['8x5 cm', '9x5 cm'],
    tags: ['art-deco', 'klasik'],
  },
  {
    id: 'template-19',
    title: 'Şablon 19',
    description: 'Minimal siyah & beyaz tipografi',
    imageUrl: '/images/personalization/template-19.jpg',
    recommendedSizes: ['5x5 cm', '6x6 cm'],
    tags: ['minimal'],
  },
  {
    id: 'template-20',
    title: 'Şablon 20',
    description: 'Sulu boya çiçek desenleri',
    imageUrl: '/images/personalization/template-20.jpg',
    recommendedSizes: ['7x7 cm', '8x6 cm'],
    tags: ['çiçek', 'romantik'],
  },
]
